# Introduction to Pandas Python

In [3]:
# Python code demonstrate creating
# DataFrame from dict narray / lists
# By default addresses.
# data dictionary를 저장하여, pandas의 data frame (df)에 넣는다.

import pandas as pd

# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}

# Create DataFrame
df = pd.DataFrame(data)

# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [4]:
# Read data from CSV file (I will ), csv/excel파일을 불러와 pandas df에 밀어 넣는다.
csv_path = "C:/Users/jk1050404/OneDrive - Bose Corporation/_MOT/파이썬프로그래밍/실습자료/TopSellingAlbums.csv"
df = pd.read_csv(csv_path)

In [5]:
# Print first five rows of the dataframe
#df.head()

# Print last five rows of the dataframe
df.tail()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [6]:
# Read data from Excel File and print the first five rows

xlsx_path = "C:/Users/jk1050404/OneDrive - Bose Corporation/_MOT/파이썬프로그래밍/실습자료/TopSellingAlbums.xlsx"

df1 = pd.read_excel(xlsx_path)
df1.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

In [7]:
# Access to the column Length, 특정데이터만 용이하게 불러온다.

x = df[['Artist']]
x

            Artist
0  Michael Jackson
1            AC/DC
2       Pink Floyd
3  Whitney Houston
4        Meat Loaf
5           Eagles
6         Bee Gees
7    Fleetwood Mac

In [8]:
# Get the column as a series

x = df['Length']
x

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object

In [9]:
# Get the column as a dataframe

x = df[['Artist']]
x

            Artist
0  Michael Jackson
1            AC/DC
2       Pink Floyd
3  Whitney Houston
4        Meat Loaf
5           Eagles
6         Bee Gees
7    Fleetwood Mac

In [10]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]
y

            Artist   Length                        Genre
0  Michael Jackson  0:42:19               pop, rock, R&B
1            AC/DC  0:42:11                    hard rock
2       Pink Floyd  0:42:49             progressive rock
3  Whitney Houston  0:57:44               R&B, soul, pop
4        Meat Loaf  0:46:33  hard rock, progressive rock
5           Eagles  0:43:08   rock, soft rock, folk rock
6         Bee Gees  1:15:54                        disco
7    Fleetwood Mac  0:40:01                    soft rock

In [11]:
# Access the value on the first row and the first column, iloc 정수위치, loc 이름으로 찾는다.

df.iloc[0, 0] #첫번째 행, 첫번째 열

'Michael Jackson'

In [12]:
# Access the column using the name

df.loc[0, 'Artist']

'Michael Jackson'

In [13]:
# Slicing the dataframe

df.iloc[0:2, 0:3] #row, column sequence

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [ ]:
# iterating over rows using iterrows() function, for루프로 모두 출력, 전체 데이터 확인 가능
for i, j in df.iterrows():
    print(i, j)
    print()

In [24]:
#Where function --> data science에서 가장 많이 사용하는 기능, 필터사용에 용이하다.

# making boolean series for the artist name
#filter1 = df["Artist"]=="Michael Jackson"
# making boolean series for Length
filter2 = df["Claimed Sales (millions)"]>42.0

# filtering data on basis of both filters
df.where(filter2)

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982.0,0:42:19,"pop, rock, R&B",46.0,65.0,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980.0,0:42:11,hard rock,26.1,50.0,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973.0,0:42:49,progressive rock,24.2,45.0,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992.0,0:57:44,"R&B, soul, pop",27.4,44.0,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977.0,0:46:33,"hard rock, progressive rock",20.6,43.0,21-Oct-77,NaN,8.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Write your code below and press Shift+Enter to execute
q = df[['Rating']]
q

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

In [26]:
# Write your code below and press Shift+Enter to execute
q = df[['Released', 'Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

In [32]:
# Write your code below and press Shift+Enter to execute
df.iloc[1, 2]

np.int64(1980)